import Head from 'next/head';
import MainLayout from '@/components/layouts/mainLayout';
import Collection1 from '@/components/Collections/Collection1/Collection1';
import Collection2 from '@/components/Collections/Collection2/Collection1';
import Collection3 from '@/components/Collections/Collection3/Collection3';

export default function Collections() {
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Collection1 />
      <Collection2 />
      <Collection3 />
    </MainLayout>
  );
}
