import Head from 'next/head';
import MainLayout from '@/components/layouts/mainLayout';
import Hero from '@/components/Hero/Hero/';
import Collection2 from '@/components/Collections/Collection2';
import Cards from '@/components/Cards/Cards';
import Grid from '@/components/Grid/Grid';

export default function Home() {
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero />
      <Cards />
      <Grid />
      <Collection2 />
    </MainLayout>
  );
}
